# this is the build file for project Lorr
# it is autogenerated by the xmake build system.
# do not edit by hand.

ifneq ($(VERBOSE),1)
VV=@
endif

MRC=/nix/store/z2kq9hrdbdqzjjsq85y11cj3v33rvvad-llvm-19.1.4/bin/llvm-rc
CXX=/nix/store/259g047ga56n7gha2d5wx20fpv9if5ak-clang-wrapper-19.1.4/bin/clang++
MXX=/nix/store/259g047ga56n7gha2d5wx20fpv9if5ak-clang-wrapper-19.1.4/bin/clang++
AS=/nix/store/259g047ga56n7gha2d5wx20fpv9if5ak-clang-wrapper-19.1.4/bin/clang
CC=/nix/store/259g047ga56n7gha2d5wx20fpv9if5ak-clang-wrapper-19.1.4/bin/clang
MM=/nix/store/259g047ga56n7gha2d5wx20fpv9if5ak-clang-wrapper-19.1.4/bin/clang

AR=/nix/store/z2kq9hrdbdqzjjsq85y11cj3v33rvvad-llvm-19.1.4/bin/llvm-ar
SH=/nix/store/259g047ga56n7gha2d5wx20fpv9if5ak-clang-wrapper-19.1.4/bin/clang++
LD=/nix/store/259g047ga56n7gha2d5wx20fpv9if5ak-clang-wrapper-19.1.4/bin/clang++

Editor_LD=/nix/store/259g047ga56n7gha2d5wx20fpv9if5ak-clang-wrapper-19.1.4/bin/clang++
Editor_CXX=/nix/store/259g047ga56n7gha2d5wx20fpv9if5ak-clang-wrapper-19.1.4/bin/clang++
Editor_CXX=/nix/store/259g047ga56n7gha2d5wx20fpv9if5ak-clang-wrapper-19.1.4/bin/clang++
Lorr_AR=/nix/store/z2kq9hrdbdqzjjsq85y11cj3v33rvvad-llvm-19.1.4/bin/llvm-ar
Lorr_CXX=/nix/store/259g047ga56n7gha2d5wx20fpv9if5ak-clang-wrapper-19.1.4/bin/clang++
Lorr_CXX=/nix/store/259g047ga56n7gha2d5wx20fpv9if5ak-clang-wrapper-19.1.4/bin/clang++
