//
// Created on Sunday 9th October 2022 by e-erdal
//

#pragma once

#include "Core/Memory/MemoryUtils.hh"

/// PIPELINE
#define LR_MAX_DESCRIPTOR_SETS_PER_PIPELINE 8
#define LR_MAX_DESCRIPTORS_PER_LAYOUT 8
#define LR_MAX_PUSH_CONSTANTS_PER_PIPELINE 8
#define LR_MAX_STATIC_SAMPLERS_PER_PIPELINE 8
#define LR_MAX_VERTEX_ATTRIBS_PER_PIPELINE 8

#define LR_MAX_RENDER_TARGET_PER_PASS 8